import { Order, ExternalRevenue, ProfitSplits } from './types';

export const SEED_ORDERS: Order[] = [];

export const SEED_REVENUES: ExternalRevenue[] = [];

export const DEFAULT_SPLITS: ProfitSplits = {
  operationalPercent: 40,
  partnersPercent: 40,
  savingsPercent: 20
};

export const DICTIONARY = {
  ar: {
    title: "سعودي كور",
    subtitle: "لوحة التحكم الذكية للطلبات والمالية والمشاريع",
    searchPlaceholder: "ابحث برقم الطلب أو اسم العميل، مشروع...",
    searchButton: "بحث",
    themeLabel: "المظهر",
    themeDark: "داكن",
    themeLight: "فاتح",
    languageLabel: "اللغة",
    settingsTitle: "الإعدادات والخيارات",
    allOrdersTab: "إدارة الطلبات",
    financeTab: "المالية والأرباح",
    newOrderPlaceholder: "طلب جديد",
    progress: "نسبة التقدم",
    paymentStatus: "حالة الدفع",
    invoiceStatus: "حالة الفاتورة تـلقائياً",
    orderStatus: "حالة الطلب",
    completedFiles: "الملفات والروابط المرفوعة",
    addAttachment: "إضافة ملف / رابط",
    uploadBtn: "رفع المرفق",
    attachName: "اسم المرفق",
    attachUrl: "رابط المرفق أو الملف",
    attachmentType: "النوع",
    file: "ملف",
    link: "رابط خارجي",
    completedConfirmation: "تم إنهاء الطلب بنجاح وتم إرسال الإشعار للعميل!",
    notifyClientSimulated: "رسالة واتس اب / رسائل نصية (محاكاة)",
    notifyPlaceholder: "سيتم إرسال رسالة آلية للعميل برقم جواله في حال تغيير حالة الطلب إلى مكتمل.",
    paymentPaid: "مدفوع",
    paymentPending: "معلق",
    paymentRefunded: "مسترجع",
    invoiceGenerated: "تم إصدارها (English)",
    invoiceDraft: "مسودة",
    orderNew: "جديد",
    orderProcessing: "قيد التنفيذ",
    orderCompleted: "مكتمل",
    orderCancelled: "ملغي",
    financeTitle: "نظام التقارير المالية والمحاسبة",
    totalProfit: "إجمالي الأرباح الكلية",
    dailyProfit: "أرباح اليوم",
    weeklyProfit: "أرباح الأسبوع",
    monthlyProfit: "أرباح الشهر",
    splitTitle: "تقسيم وتوزيع الأرباح",
    opPercent: "نسبة المصاريف التشغيلية",
    partPercent: "نسبة الشركاء والمستشارين",
    savePercent: "نسبة الاحتياطي والادخار",
    recalculate: "حفظ وتحديث التقسيم",
    addedToFinance: "تضاف فواتير الطلبات المدفوعة والمكتملة تلقائياً للأرباح",
    externalProfitTitle: "تسجيل الأرباح الخارجية الأخرى",
    externalAmount: "قيمة المبلغ المالي (SAR)",
    externalDesc: "بيان الربح / الوصف للإيراد",
    externalCat: "التصنيف",
    addRevBtn: "إضافة إيراد خارجي",
    recentTransactions: "أحدث العمليات والمدخولات",
    invoiceHeader: "الفاتورة الإلكترونية التلقائية",
    viewInvoice: "عرض الفاتورة",
    invoiceLanguageTip: "تُصدر الفواتير تلقائياً باللغة الإنجليزية ومتناسبة مع رقم الطلب الإلكتروني.",
    clientDetails: "بيانات العميل",
    email: "البريد الإلكتروني",
    phone: "رقم الجوال",
    projectScope: "تفاصيل المشروع والطلب",
    changeHistory: "تحديثات النظام",
    noResults: "عذراً.. لا توجد نتائج مطابقة لبحثك.",
    floatingBubbleTooltip: "انقر لفتح الإعدادات والتحكم بالمظهر واللغة",
    savedAlert: "تم حفظ الإعدادات والبيانات بنجاح",
    close: "إغلاق",
    printInvoice: "طباعة الفاتورة",
    mockSmsSent: "تم إرسال رسالة جوال آلية للعميل بنجاح!",
    sar: "ريال سعودي",
    activeRevenueSource: "مصدر الدخل",
    originalInvoice: "فاتورة طلب رقم",
    externalRevenueSource: "دخْل خارجي",
    progressRequired: "عند اكتمال المشروع بنسبة 100% وتغيير الحالة لمكتمل، يمكنك إرفاق تليمات العمل النهائية.",
    notificationTitle: "تفاصيل الإشعار المرسل للعميل",
    notificationContent: "نص الرسالة التي أرسلت تلقائياً للعميل:"
  },
  en: {
    title: "Saudi Core",
    subtitle: "Smart Management Portal for Orders & Accounting",
    searchPlaceholder: "Search by order number, client name, project...",
    searchButton: "Search",
    themeLabel: "Appearance",
    themeDark: "Dark",
    themeLight: "Light",
    languageLabel: "Language",
    settingsTitle: "Configuration & Services",
    allOrdersTab: "Orders Desk",
    financeTab: "Earning & Ledger",
    newOrderPlaceholder: "New Request",
    progress: "Project Progress",
    paymentStatus: "Payment",
    invoiceStatus: "E-Invoice (Auto)",
    orderStatus: "Order Status",
    completedFiles: "Completed Delivery Assets",
    addAttachment: "Attach Asset / Link",
    uploadBtn: "Add Attachment",
    attachName: "Asset Name",
    attachUrl: "Asset URL or file link",
    attachmentType: "Type",
    file: "File",
    link: "URL Link",
    completedConfirmation: "Order completed! Simulated customer mobile alert dispatched.",
    notifyClientSimulated: "Simulated Mobile / SMS Dispatch Center",
    notifyPlaceholder: "A simulated automated cellular message is sent to the client’s phone code once active state hits completed.",
    paymentPaid: "Paid",
    paymentPending: "Pending",
    paymentRefunded: "Refunded",
    invoiceGenerated: "Generated (EN)",
    invoiceDraft: "Draft",
    orderNew: "New Request",
    orderProcessing: "Processing",
    orderCompleted: "Completed",
    orderCancelled: "Cancelled",
    financeTitle: "Financial Reports & Simple Ledger",
    totalProfit: "Total Platform Earnings",
    dailyProfit: "Earning Today",
    weeklyProfit: "Earning This Week",
    monthlyProfit: "Earning This Month",
    splitTitle: "Automated Profit Ledger Splits",
    opPercent: "Operational Run Costs %",
    partPercent: "Partners/Consultants %",
    savePercent: "Reserve Savings Savings %",
    recalculate: "Save & Apportion Splitting",
    addedToFinance: "Completed & Paid digital orders are integrated automatically inside profits",
    externalProfitTitle: "Record External Supplementary Inflow",
    externalAmount: "Amount Value (SAR)",
    externalDesc: "Inward Description / Reference",
    externalCat: "Inward Segment",
    addRevBtn: "Inject Inward Earning",
    recentTransactions: "Historical Ledger Streams",
    invoiceHeader: "Automated E-Invoice Document",
    viewInvoice: "View E-Invoice",
    invoiceLanguageTip: "Invoices generated systematically in English based on the secure platform sequence code.",
    clientDetails: "Client Profile",
    email: "Email Address",
    phone: "Mobile Phone",
    projectScope: "Project Technical Scope",
    changeHistory: "System Logs",
    noResults: "No matching criteria matches your query query.",
    floatingBubbleTooltip: "Click to open customization, localization & settings menu",
    savedAlert: "Local state persistent state variables updated",
    close: "Close Window",
    printInvoice: "Print Document",
    mockSmsSent: "Simulated automated SMS dispatched to the customer's device successfully!",
    sar: "SAR",
    activeRevenueSource: "Platform Order Inflow",
    originalInvoice: "Original Invoice #",
    externalRevenueSource: "External Auxiliary Rev",
    progressRequired: "Once project progress is updated to 100% and marked completed, delivery files/links can be associated.",
    notificationTitle: "Customer Mobile Dispatch Logs",
    notificationContent: "Dispatched automated cellular template payload:"
  }
};
